<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="ekalavya">

<!-- macros for inertial blocks -->
<xacro:macro name="inertial_box" params="mass x y z *origin">
    <inertial>
        <xacro:insert_block name="origin"/>
        <mass value="${mass}" />
        <inertia ixx="${(1/12) * mass * (y*y+z*z)}" ixy="0.0" ixz="0.0"
                iyy="${(1/12) * mass * (x*x+z*z)}" iyz="0.0"
                izz="${(1/12) * mass * (x*x+y*y)}" />
    </inertial>
</xacro:macro>


<xacro:macro name="inertial_cylinder" params="mass length radius *origin">
    <inertial>
        <xacro:insert_block name="origin"/>
        <mass value="${mass}" />
        <inertia ixx="${(1/12) * mass * (3*radius*radius + length*length)}" ixy="0.0" ixz="0.0"
                iyy="${(1/12) * mass * (3*radius*radius + length*length)}" iyz="0.0"
                izz="${(1/2) * mass * (radius*radius)}" />
    </inertial>
</xacro:macro>
<!-- end of macros -->

<link name="base_link"></link>

<!-- chassis -->
<!-- car parameters -->
<xacro:property name="car_length" value="1"/>
<xacro:property name="car_width" value="0.5"/>
<xacro:property name="car_height" value="0.25"/>

<joint name="base_to_chassis_joint" type="fixed">
    <parent link="base_link"/>
    <child link="chassis_link"/>
    <origin xyz="${car_length/2} 0.0 ${car_height/2}" rpy="0.0 0.0 0.0"/>
</joint>


<link name="chassis_link">
    <visual>
        <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
        <geometry>
            <box size="${car_length} ${car_width} ${car_height}"/>
        </geometry>
    </visual>
    <collision>
        <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
        <geometry>
            <box size="${car_length} ${car_width} ${car_height}"/>
        </geometry>
    </collision>
    <xacro:inertial_box mass="1" x="${car_length}" y="${car_width}" z="${car_height}">
        <origin xyz="0.0 0 0" rpy="0 0 0"/>
    </xacro:inertial_box>
</link>


<!-- wheels -->
<!-- wheel properties -->
<xacro:property name="wheel_radius" value="${car_height/2.5}"/>
<xacro:property name="wheel_length" value="${car_width/7}"/>

<!-- left wheel1 -->
<joint name="chassis_to_left_wheel1_joint" type="continuous">
    <parent link="chassis_link"/>
    <child link="left_wheel1_link"/>
    <axis xyz="0 0 1"/>
    <origin xyz="${car_length/3} ${car_width/2 + wheel_length/2} ${-car_height/2}" rpy="${-pi/2} 0 0"/>
</joint>


<link name="left_wheel1_link">
    <visual>
        <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
        <geometry>
            <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
        </geometry>
    </visual>
    <collision>
        <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
        <geometry>
            <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
        </geometry>
    </collision>
    <xacro:inertial_cylinder mass="0.25" length="${wheel_length}" radius="${wheel_radius}">
        <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
    </xacro:inertial_cylinder>
</link>

<!-- left wheel2 -->
<joint name="chassis_to_left_wheel2_joint" type="continuous">
    <parent link="chassis_link"/>
    <child link="left_wheel2_link"/>
    <axis xyz="0 0 1"/>
    <origin xyz="${-car_length/3} ${car_width/2 + wheel_length/2} ${-car_height/2}" rpy="${-pi/2} 0 0"/>
</joint>


<link name="left_wheel2_link">
    <visual>
        <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
        <geometry>
            <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
        </geometry>
    </visual>
        <collision>
        <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
        <geometry>
            <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
        </geometry>
    </collision>
    <xacro:inertial_cylinder mass="0.25" length="${wheel_length}" radius="${wheel_radius}">
        <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
    </xacro:inertial_cylinder>
</link>

<!-- right wheel1 -->
<joint name="chassis_to_right_wheel1_joint" type="continuous">
    <parent link="chassis_link"/>
    <child link="right_wheel1_link"/>
    <axis xyz="0 0 -1"/>
    <origin xyz="${car_length/3} ${-car_width/2 - wheel_length/2} ${-car_height/2}" rpy="${pi/2} 0 0"/>
</joint>


<link name="right_wheel1_link">
    <visual>
        <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
        <geometry>
            <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
        </geometry>
    </visual>
    <collision>
        <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
        <geometry>
            <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
        </geometry>
    </collision>
    <xacro:inertial_cylinder mass="0.25" length="${wheel_length}" radius="${wheel_radius}">
        <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
    </xacro:inertial_cylinder>
</link>


<!-- left wheel2 -->
<joint name="chassis_to_right_wheel2_joint" type="continuous">
    <parent link="chassis_link"/>
    <child link="right_wheel2_link"/>
    <axis xyz="0 0 -1"/>
    <origin xyz="${-car_length/3} ${-car_width/2 - wheel_length/2} ${-car_height/2}" rpy="${pi/2} 0 0"/>
</joint>


<link name="right_wheel2_link">
    <visual>
        <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
        <geometry>
            <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
        </geometry>
    </visual>
    <collision>
        <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
        <geometry>
            <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
        </geometry>
    </collision>
    <xacro:inertial_cylinder mass="0.25" length="${wheel_length}" radius="${wheel_radius}">
        <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
    </xacro:inertial_cylinder>
</link>

</robot>
